export enum ServiceType {
  LAMP_REPLACEMENT = 'LAMP_REPLACEMENT',
  ROAD_REPAIR = 'ROAD_REPAIR',
  GARBAGE_COLLECTION = 'GARBAGE_COLLECTION',
  STREET_CLEANING = 'STREET_CLEANING',
  TREE_TRIMMING = 'TREE_TRIMMING',
  PARK_MAINTENANCE = 'PARK_MAINTENANCE',
}
